### ISSUE TITLE
Feature request: Please Add Moving Average

### ISSUE THREAD

**Issue by loretoparisi** [stig/Statistics#9]
Could you please add moving average to stats?
Here is a possible implementation taken from: http://stackoverflow.com/questions/8447868/calculating-moving-averages-of-variable-parameters

I have added in the interface the `samples` private array, count and average size:

``` objective-c
/// Sparse statistics class
@interface SBStatistics : NSObject {
    NSUInteger count;
    NSUInteger mindex;
    NSUInteger maxdex;

    double min;
    double max;
    double mean;

@private
    double pseudoVariance;
    NSMutableArray *samples;
    int sampleCount;
    int averageSize;
}
```

Added a new custom init wth `size` samples

``` objective-c
- (id)initWithSize:(int)size
{

    if (self = [super init]) {
        samples = [[NSMutableArray alloc] initWithCapacity:size];
        sampleCount = 0;
        averageSize = size;
    }
    return self;
}
```

where the defaults

``` objective-c
- (id)init
{
    self = [super init];
    if (self) {
        //min = max = mean = nan(0);
        min = max = count = mean = averageSize = sampleCount = 0;
    }
    return self;
}
```

and in the `addDouble`

``` objective-c
- (void)addDouble:(double)d {
    if (!count) {
        min = INFINITY;
        max = -min;
        mean = 0;
    }

    if (d < min) {
        min = d;
        mindex = count;
    }
    if (d > max) {
        max = d;
        maxdex = count;
    }

    double oldMean = mean;
    mean += (d - oldMean) / ++count;
    pseudoVariance += (d - mean) * (d - oldMean);

    if(averageSize>0) {
        int pos = fmodf(sampleCount++, (float)averageSize);
        [samples setObject:[NSNumber numberWithDouble:sample] atIndexedSubscript:pos];
    }
}
```

the calculation is then

``` objective-c
// @see 
- (double)movingAverage
{
    NSAssert([samples count], @"No mean values");
    return [[samples valueForKeyPath:@"@sum.doubleValue"] doubleValue]/(sampleCount > averageSize-1?averageSize:sampleCount);
}
```

**Comment by stig** [comment]
Hi @loretoparisi,

Moving average could be an interesting thing to add. I regretfully don't have time to add this myself, but I would consider merging a PR if you are interested in contributing an implementation. 

I wonder if it would make sense to add it to the `SBFullStatistics` class, which already retains the data points? That would allow you to get the moving average of N data points at any time, i.e. you could calculate both the 10 moving average and 20 moving average rather than just a single pre-chosen one. It's more general, but perhaps not ideal if you have a lot of data points and just want moving average for a short window. Something to think about!

**Comment by loretoparisi** [comment]
So, yes looking better at the code, the best place should be ```SBFullStatistics```. There are a lot of stats tools out there, but sometimes small tools like yours are best. I think it should be generic so as soon as you add data points it recalculates the MA on the interval size you have defined at some point.
